# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InformedCitizen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Networking', '~> 4'
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'CryptoSwift'
  pod 'Kingfisher'
  pod 'RealmSwift'

  target 'InformedCitizenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InformedCitizenUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
